In [11]:
import pandas as pd

df = pd.read_csv("../data/processed/fraud_processed.csv")
df.head()

,user_id,purchase_value,source,browser,sex,age,ip_address,class,hour,lower_bound_ip_address,upper_bound_ip_address,country,time_since_signup,hour_of_day,day_of_week,user_transaction_count,device_transaction_count,ip_transaction_count
0,247547,47,SEO,Safari,F,30,16778864,0,3,16778240.0,16779263.0,Australia,1008.948611,3,6,1,1,1
1,220737,15,SEO,Chrome,F,34,16842045,0,20,16809984.0,16842751.0,Thailand,342.121389,20,2,1,1,1
2,390400,44,Ads,IE,M,29,16843656,0,23,16843264.0,16843775.0,China,554.870556,23,5,1,2,1
3,69592,55,Direct,Chrome,F,30,16938732,0,16,16924672.0,16941055.0,China,2122.471389,16,5,1,1,1
4,174987,51,SEO,Chrome,F,37,16971984,0,4,16941056.0,16973823.0,Thailand,2847.105278,4,1,1,1,1

In [12]:
X = df.drop("class", axis=1)
y = df["class"]

In [13]:
X = pd.get_dummies(X, drop_first=True)

X = pd.get_dummies(X, drop_first=True)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

SCALE NUMERICAL FEATURES

In [15]:
from sklearn.preprocessing import StandardScaler

num_cols = [
    "purchase_value",
    "age",
    "time_since_signup",
    "user_transaction_count",
    "device_transaction_count",
    "ip_transaction_count"
]

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

SMOTE

In [16]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

LOGISTIC REGRESSION

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix, average_precision_score

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_smote, y_train_smote)

y_pred_lr = lr_model.predict(X_test)
y_proba_lr = lr_model.predict_proba(X_test)[:, 1]

Evaluation

In [18]:
print("Logistic Regression Results")
print("F1 Score:", f1_score(y_test, y_pred_lr))
print("AUC-PR:", average_precision_score(y_test, y_proba_lr))
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Results
F1 Score: 0.16487985212569317
AUC-PR: 0.09543579657648502
[[10938 12438]
 [ 1116  1338]]

RANDOM FOREST

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_smote, y_train_smote)

y_pred_rf = rf_model.predict(X_test)
y_proba_rf = rf_model.predict_proba(X_test)[:, 1]

In [20]:
print("Random Forest Results")
print("F1 Score:", f1_score(y_test, y_pred_rf))
print("AUC-PR:", average_precision_score(y_test, y_proba_rf))
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Results
F1 Score: 0.6504520017219113
AUC-PR: 0.7131220902352422
[[22695   681]
 [  943  1511]]

XGBOOST

In [21]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train_smote, y_train_smote)

y_pred_xgb = xgb_model.predict(X_test)
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

In [22]:
print("XGBoost Results")
print("F1 Score:", f1_score(y_test, y_pred_xgb))
print("AUC-PR:", average_precision_score(y_test, y_proba_xgb))
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Results
F1 Score: 0.6931732933233309
AUC-PR: 0.7011878195187234
[[23217   159]
 [ 1068  1386]]

In [23]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest", "XGBoost"],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb) if 'xgb_model' in globals() else None
    ],
    "AUC-PR": [
        average_precision_score(y_test, y_proba_lr),
        average_precision_score(y_test, y_proba_rf),
        average_precision_score(y_test, y_proba_xgb) if 'xgb_model' in globals() else None
    ]
})

results

                 Model  F1 Score    AUC-PR
0  Logistic Regression  0.164880  0.095436
1        Random Forest  0.650452  0.713122
2              XGBoost  0.693173  0.701188

Logistic Regression is used as a baseline model due to its simplicity and interpretability. Random Forest and XGBoost capture non-linear patterns and interactions between behavioral and transactional features. Performance is evaluated using F1-score and AUC-PR due to severe class imbalance.

In [24]:
rf_model.feature_importances_

array([6.25628303e-03, 6.00986640e-03, 5.59316032e-03, 3.96359377e-03,
       6.89092200e-03, 3.61792629e-03, 3.46837381e-03, 1.87037422e-01,
       5.55054008e-03, 7.90042047e-03, 0.00000000e+00, 3.99108247e-01,
       2.74002238e-01, 2.00972703e-02, 1.45154578e-02, 9.60692551e-03,
       9.36803009e-03, 1.35601321e-03, 8.75070845e-03, 1.25162179e-02,
       2.59938289e-06, 1.47193560e-04, 9.34241030e-06, 1.34264468e-08,
       1.04279673e-04, 3.97541219e-05, 2.34495748e-04, 6.60016115e-05,
       2.58234213e-05, 0.00000000e+00, 1.01896000e-07, 1.75004217e-05,
       0.00000000e+00, 1.03425606e-05, 2.64818761e-04, 0.00000000e+00,
       3.26770118e-10, 0.00000000e+00, 0.00000000e+00, 4.74588880e-05,
       1.22503909e-07, 2.72236115e-06, 8.48096992e-07, 1.45150273e-04,
       0.00000000e+00, 0.00000000e+00, 1.67498209e-05, 0.00000000e+00,
       0.00000000e+00, 9.60422802e-09, 2.72660349e-08, 7.85081685e-04,
       0.00000000e+00, 7.09829208e-10, 2.65804592e-04, 6.77138524e-04,
       8.01018791e-05, 0.00000000e+00, 0.00000000e+00, 3.81378620e-05,
       2.77193966e-05, 7.37811228e-05, 0.00000000e+00, 0.00000000e+00,
       6.91799648e-06, 7.25638975e-05, 4.77030700e-04, 0.00000000e+00,
       0.00000000e+00, 7.04951320e-06, 1.17322759e-04, 1.36099595e-04,
       3.68335657e-06, 2.01663344e-06, 1.24919414e-07, 5.05041904e-05,
       2.47422995e-09, 0.00000000e+00, 1.43311782e-04, 2.27531365e-04,
       2.25535155e-06, 0.00000000e+00, 7.98268541e-06, 4.47264924e-04,
       8.75986558e-07, 0.00000000e+00, 1.46860976e-04, 0.00000000e+00,
       0.00000000e+00, 2.47707653e-06, 6.29678135e-07, 4.55963059e-06,
       3.77429351e-04, 6.05389106e-05, 1.64763072e-05, 2.17847491e-04,
       1.12985796e-04, 2.14246997e-04, 1.20691303e-06, 4.50914370e-04,
       7.16192813e-05, 2.88476913e-04, 1.81626573e-06, 4.90373431e-04,
       4.41789677e-09, 5.34442630e-05, 1.81418110e-05, 5.08521464e-04,
       9.37055022e-05, 3.50866033e-06, 7.50945430e-07, 3.28169069e-05,
       3.23649434e-05, 0.00000000e+00, 2.47246271e-05, 4.66775329e-09,
       1.07915039e-04, 2.04872375e-04, 0.00000000e+00, 5.61708218e-06,
       0.00000000e+00, 1.34668924e-05, 4.63086640e-05, 5.44882408e-07,
       5.67465179e-05, 7.97392976e-07, 1.96254481e-04, 1.21524124e-05,
       2.76748334e-06, 2.07453833e-06, 9.01898896e-06, 2.95747659e-05,
       3.02892941e-06, 0.00000000e+00, 6.75643197e-05, 0.00000000e+00,
       1.67802635e-06, 1.36393472e-04, 2.98379126e-08, 3.63099448e-04,
       2.15731222e-05, 0.00000000e+00, 5.41119450e-05, 3.09362176e-04,
       3.66660819e-06, 2.48976968e-05, 1.42988635e-06, 1.46057849e-05,
       0.00000000e+00, 4.89916341e-06, 1.27020172e-04, 9.47817765e-05,
       1.73591886e-04, 5.01696263e-05, 1.09249263e-06, 3.64536364e-07,
       0.00000000e+00, 8.21527520e-05, 3.52214805e-04, 8.50942441e-08,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.57877243e-04,
       5.72200928e-06, 7.66219889e-06, 3.92119939e-05, 3.81921763e-05,
       3.79417568e-05, 2.96239004e-05, 1.85207987e-04, 3.72037139e-09,
       1.41966795e-04, 1.31219327e-04, 1.55200439e-05, 2.41047568e-04,
       1.12725147e-04, 9.63231500e-07, 1.79995378e-04, 0.00000000e+00,
       2.42917998e-06, 4.29125791e-05, 1.65891113e-05, 1.25188894e-04,
       8.74635183e-05, 1.14637853e-06, 2.03437823e-09, 1.40054680e-04,
       3.60596929e-05, 6.43486528e-04, 1.12912120e-03, 2.02679157e-05,
       5.01694795e-06, 0.00000000e+00, 1.31669263e-04, 7.63419643e-05,
       1.91877194e-05, 0.00000000e+00, 7.91392449e-08, 4.52987034e-07])